### PR TITLE
Customizable restic user

### PR DESCRIPTION
**Pull request by enricostano**
Right now restic is executed as `root` by default, with this PR I would like to propose a way to customize this setting.

By default the restic user would still be `root`, but we could allow to set up specific user.

What do you think? Thanks!

### CODE REVIEW

**Comment by enricostano** [comment]
I just noticed that you can specify a `user` key in each cron job, this would probably cover my needs.

**Comment by enricostano** [comment]
The main problem is that if we specify a custom user in a cron job `user` key the cron job will fail since the password file can be only read by `root`.

**Comment by donat-b** [comment]
You're right, I'm going to look into that to make sure user switching works.

**Comment by enricostano** [comment]
Thanks! Here is my temporary/hackish solution 😂:
https://github.com/coopdevs/katuma-provisioning/pull/9/files#diff-d36f16a0149ca782d6d17c914a02b658R39

**Comment by paulfantom** [comment]
Or maybe we could apply #15?

**Comment by donat-b** [comment]
I have researched a little on the environment security and now I as well lean towards removing password files.

**Comment by donat-b** [comment]
@enricostano 
Added your proposed changes :)

**Pull request closed without merging**
